# cheese brand seeds
CheeseBrand.create(name: "Kraft")
CheeseBrand.create(name: "Cabot")
CheeseBrand.create(name: "Organic Valley")
CheeseBrand.create(name: "Sargento")
CheeseBrand.create(name: "Stella")

# cheese seeds
Cheese.create(name: "Brie", cheese_brand_id: 2)
Cheese.create(name: "Cheddar", cheese_brand_id: 3)
Cheese.create(name: "Colby-Jack", cheese_brand_id: 3)
Cheese.create(name: "Monterey Jack", cheese_brand_id: 3)
Cheese.create(name: "Mozzarella", cheese_brand_id: 3)
Cheese.create(name: "Swiss", cheese_brand_id: 3)
Cheese.create(name: "Muenster", cheese_brand_id: 3)
Cheese.create(name: "Pepper Jack", cheese_brand_id: 3)
Cheese.create(name: "Bleu", cheese_brand_id: 4)
Cheese.create(name: "Cheddar", cheese_brand_id: 4)
Cheese.create(name: "Colby-Jack", cheese_brand_id: 4)
Cheese.create(name: "Feta", cheese_brand_id: 4)
Cheese.create(name: "Monterey Jack", cheese_brand_id: 4)
Cheese.create(name: "Swiss", cheese_brand_id: 4)
Cheese.create(name: "Farmers", cheese_brand_id: 4)
Cheese.create(name: "Provolone", cheese_brand_id: 4)
Cheese.create(name: "Cheddar", cheese_brand_id: 5)
Cheese.create(name: "Colby-Jack", cheese_brand_id: 5)
Cheese.create(name: "Monterey Jack", cheese_brand_id: 5)
Cheese.create(name: "Muenster", cheese_brand_id: 5)
Cheese.create(name: "Provolone", cheese_brand_id: 5)
Cheese.create(name: "Swiss", cheese_brand_id: 5)
Cheese.create(name: "Baby", cheese_brand_id: 6)
Cheese.create(name: "Mozzarella", cheese_brand_id: 6)
Cheese.create(name: "Cheddar", cheese_brand_id: 6)
Cheese.create(name: "Bleu", cheese_brand_id: 6)

# wine brand seeds
WineBrand.create(name: "Two-Buck-Chuck", company: "Trader Joes")
WineBrand.create(name: "Stature", company: "Kendall-Jackson")
WineBrand.create(name: "Catena", company: "High Mountain Vines")
WineBrand.create(name: "Sharrott", company: "Sharrott Winery")
WineBrand.create(name: "Hollington", company: "Flack Winery")
WineBrand.create(name: "Flatiron", company: "Kriscotanda")

# category seeds
Category.create(name: "Cabernet Sauvignon")
Category.create(name: "Chardonnay")
Category.create(name: "Malbec")
Category.create(name: "Pinot Noir")

# region seeds
Region.create(name: "Argentina")
Region.create(name: "New Jersey")
Region.create(name: "California")
Region.create(name: "England")
Region.create(name: "New York")

# wine seeds
Wine.create(wine_brand_id: 5, category_id: 1, region_id: 4, year: 1982)
Wine.create(wine_brand_id: 1, category_id: 2, region_id: 2, year: 2014)
Wine.create(wine_brand_id: 1, category_id: 2, region_id: 2, year: 2014)
Wine.create(wine_brand_id: 2, category_id: 1, region_id: 3, year: 2012)
Wine.create(wine_brand_id: 2, category_id: 6, region_id: 3, year: 2013)
Wine.create(wine_brand_id: 3, category_id: 3, region_id: 1, year: 2013)
Wine.create(wine_brand_id: 4, category_id: 1, region_id: 2, year: 2013)
Wine.create(wine_brand_id: 5, category_id: 2, region_id: 4, year: 2013)
Wine.create(wine_brand_id: 5, category_id: 3, region_id: 4, year: 2012)
Wine.create(wine_brand_id: 3, category_id: 2, region_id: 1, year: 2011)
Wine.create(wine_brand_id: 6, category_id: 4, region_id: 5, year: 2016)
Wine.create(wine_brand_id: 6, category_id: 1, region_id: 5, year: 2013)
Wine.create(wine_brand_id: 6, category_id: 2, region_id: 5, year: 2014)
Wine.create(wine_brand_id: 6, category_id: 3, region_id: 5, year: 2015)

# pairing seeds
Pairing.create(wine_id: 1, cheese_id: 1)
Pairing.create(wine_id: 1, cheese_id: 2)
Pairing.create(wine_id: 1, cheese_id: 3)
Pairing.create(wine_id: 1, cheese_id: 4)
Pairing.create(wine_id: 1, cheese_id: 5)
Pairing.create(wine_id: 1, cheese_id: 6)
Pairing.create(wine_id: 1, cheese_id: 7)
Pairing.create(wine_id: 1, cheese_id: 8)
Pairing.create(wine_id: 1, cheese_id: 9)
Pairing.create(wine_id: 1, cheese_id: 10)
Pairing.create(wine_id: 1, cheese_id: 11)
Pairing.create(wine_id: 1, cheese_id: 12)
Pairing.create(wine_id: 1, cheese_id: 13)
Pairing.create(wine_id: 1, cheese_id: 14)
Pairing.create(wine_id: 2, cheese_id: 1)
Pairing.create(wine_id: 2, cheese_id: 2)
Pairing.create(wine_id: 2, cheese_id: 3)
Pairing.create(wine_id: 2, cheese_id: 4)
Pairing.create(wine_id: 2, cheese_id: 5)
Pairing.create(wine_id: 2, cheese_id: 6)
Pairing.create(wine_id: 2, cheese_id: 7)
Pairing.create(wine_id: 2, cheese_id: 8)
Pairing.create(wine_id: 2, cheese_id: 9)
Pairing.create(wine_id: 2, cheese_id: 10)
Pairing.create(wine_id: 2, cheese_id: 11)
Pairing.create(wine_id: 2, cheese_id: 12)
Pairing.create(wine_id: 2, cheese_id: 13)
Pairing.create(wine_id: 2, cheese_id: 14)
Pairing.create(wine_id: 3, cheese_id: 3)
Pairing.create(wine_id: 4, cheese_id: 4)
Pairing.create(wine_id: 5, cheese_id: 5)
Pairing.create(wine_id: 6, cheese_id: 6)
Pairing.create(wine_id: 7, cheese_id: 7)
Pairing.create(wine_id: 8, cheese_id: 8)
Pairing.create(wine_id: 9, cheese_id: 9)
Pairing.create(wine_id: 10, cheese_id: 10)
Pairing.create(wine_id: 11, cheese_id: 11)
Pairing.create(wine_id: 12, cheese_id: 12)
Pairing.create(wine_id: 13, cheese_id: 13)
Pairing.create(wine_id: 14, cheese_id: 14)
Pairing.create(wine_id: 2, cheese_id: 15)
Pairing.create(wine_id: 5, cheese_id: 16)
Pairing.create(wine_id: 3, cheese_id: 17)
Pairing.create(wine_id: 4, cheese_id: 18)
Pairing.create(wine_id: 5, cheese_id: 19)
Pairing.create(wine_id: 1, cheese_id: 20)
Pairing.create(wine_id: 6, cheese_id: 21)
Pairing.create(wine_id: 3, cheese_id: 22)
Pairing.create(wine_id: 7, cheese_id: 23)
Pairing.create(wine_id: 8, cheese_id: 24)
Pairing.create(wine_id: 9, cheese_id: 25)
Pairing.create(wine_id: 10, cheese_id: 26)

# user seeds
User.create(name: "Krissa", age: 24, email: "krissa@krissa.com", password: "krissa")
User.create(name: "Scott", age: 34, email: "scott@scott.com", password: "scott")
User.create(name: "Amanda", age: 98, email: "amanda@amanda.com", password: "amanda")
User.create(name: "Jeff", age: 21, email: "jeff@jeff.com", password: "jeff")
User.create(name: "Sam", age: 80, email: "sam@sam.com", password: "sam")
User.create(name: "Leigh", age: 45, email: "leigh@leigh.com", password: "leigh")
User.create(name: "Cody", age: 56, email: "cody@cody.com", password: "cody")
User.create(name: "Giselle", age: 32, email: "giselle@giselle.com", password: "giselle")
User.create(name: "Holli", age: 25, email: "holli@holli.com", password: "holli")

# poster seeds
Poster.create(user_id: 1)
Poster.create(user_id: 2)
Poster.create(user_id: 3)
Poster.create(user_id: 4)
Poster.create(user_id: 5)
Poster.create(user_id: 6)
Poster.create(user_id: 7)
Poster.create(user_id: 8)
Poster.create(user_id: 9)

# reviewer seeds
Reviewer.create(user_id: 1)
Reviewer.create(user_id: 2)
Reviewer.create(user_id: 3)
Reviewer.create(user_id: 4)
Reviewer.create(user_id: 5)
Reviewer.create(user_id: 6)
Reviewer.create(user_id: 7)
Reviewer.create(user_id: 8)
Reviewer.create(user_id: 9)

# posts seeds
Post.create(poster_id: 1, pairing_id: 1, title: "My First Pairing!", content: "Hey all. This is my first pairing. I am really into wine and cheese because they really compliment each other. I hope you enjoyed my first pairing post.")

Post.create(poster_id: 1, pairing_id: 4, title: "Second Pairing!", content: "I have really enjoyed Hollington Cabernet Sauvignon with Organic Valley Monterey Jack. It's a great combo and especially good at a dinner party. All of my friends loved it. This site rules!")

Post.create(poster_id: 2, pairing_id: 6, title: "Hey", content: "Wow, do I love my wine and cheese! I can't believe I haven't tried this combo before. I thought I tried every pairing on the planet but this one is probably my favorite. I am going to suggest this to all my chef friends.")

Post.create(poster_id: 2, pairing_id: 8, title: "Meh", content: "Okay, so this paring was just meh. It wasn't the best. I think it was a bit dull and the wine just REALLY didn't go with the cheese. I hope my next pairing is better. Would love to hear your thoughts.")

Post.create(poster_id: 3, pairing_id: 6, title: "Love this", content: "I think I've found the perfect wine and cheese pairing. I have recommended this to everyone I know who enjoys wine and cheese. It's ridiculously good!!! Amazing!")

Post.create(poster_id: 4, pairing_id: 3, title: "Hate wine and cheese now", content: "After trying this wine and cheese pairing, I've decided I no longer like wine and cheese together now! Yuck! Ew! Gross!!!!!")

Post.create(poster_id: 4, pairing_id: 6, title: "Ok...", content: "Okay, I think I overreacted in my last post. I actually love this pairing and am back into wine and cheese pairings now. Yay for wine and cheese!!!")

Post.create(poster_id: 5, pairing_id: 7, title: "Like it", content: "My sister got me into this pairing. I think it's really nice and great for a quiet night in.")

Post.create(poster_id: 6, pairing_id: 7, title: "This is good", content: "I introduced my brother to this wine and cheese pairing. I love it! I think he loves it too. It's a really great combination of wine and cheese and I hope other people see this post and try it.")

# review seeds
Review.create(post_id: 1, reviewer_id: 3, title: "Thanks!", content: "Totally enjoyed your first pairing!")

Review.create(post_id: 1, reviewer_id: 4, title: "Cool", content: "Enjoyed your first pairing. Thanks for sharing.")

Review.create(post_id: 6, reviewer_id: 1, title: "Same here", content: "I don't like this pairing either.")

Review.create(post_id: 6, reviewer_id: 5, title: "Really?!", content: "Wow! I can't believe this! I love this pairing!")
